### PR TITLE
Add support for building with meson

### PR DESCRIPTION
**Pull request by Cogitri**

### CODE REVIEW

**Comment by Geod24** [comment]
At this point, wouldn't it be more interesting for you to look at https://github.com/dlang/dub/issues/1866 ?

**Comment by Geod24** [comment]
Not familiar with meson myself, maybe @PetarKirov can take a look ?

**Comment by Cogitri** [comment]
> At this point, wouldn't it be more interesting for you to look at dlang/dub#1866 ?

That does sound very interesting, but will probably take a little longer to implement.

**Comment by Cogitri** [comment]
One thing that isn't handled in this yet is the configurations dub supports, because I'm not quite sure how to best do that. Should users be able to enable those themselves, or should they be enabled automagically (per platform?)

**Pull request merged**
