### PR TITLE
Add MSG_NOSIGNAL flag to send call to avoid SIGPIPE

### LINKED ISSUE #127: SIGPIPE on send
in `posix/sockets.d`: `send` is used for sending data over a socket, with `0` being passed as flags. However for stream-oriented sockets the `EPIPE` error results in a `SIGPIPE` being raised, exiting the process. The `MSG_NOSIGNAL` flag should be used to prevent this.

### PR DESCRIPTION
**Pull request by BenjaminSchaaf**
Fixes #127

### CODE REVIEW

**Comment by s-ludwig** [comment]
Looks like macOS requires the use of `SO_NOSIGPIPE`, even though FreeBSD does support `MSG_NOSIGNAL`.

**Comment by ZombineDev** [comment]
@s-ludwig CI has passed -> you can now either merge manually or reapply the `auto-merge` label.

**Comment by s-ludwig** [comment]
`SO_NOSIGPIPE` needs to be set using `setsockopt` once after socket creation instead of passing it to `send`:
```
int val = 1;
setsockopt(sockfd, SOL_SOCKET, SO_NOSIGPIPE, &val, val.sizeof);
```

**Comment by BenjaminSchaaf** [comment]
@s-ludwig Ah sorry, should have looked that one up :man_facepalming:. We should probably also use the send flags on all the send calls.

**Pull request merged**
