### PR TITLE
implement IOMode.once in posix file read

### PR DESCRIPTION
**Pull request by WebFreak001**

### CODE REVIEW

**Comment by s-ludwig** [comment]
Wouldn't a simple test case that doesn't use up the whole memory resources of the test machine look something like this:
- create file with 16 bytes
- open file
- attempt to read 32 bytes with IOMode.once

I don't know whether the amount of physical RAM is also a hard limit on some systems, but I would have *guessed* that it shouldn't matter when there is additional swap memory.

**Comment by WebFreak001** [comment]
already without this change a small file with a bigger buffer would end there. This change makes it so that when the buffer is larger than what a single read call will fill, it will stop there and not attempt to read the rest of the file or fill up the buffer, like it does with IOMode.all

**Comment by s-ludwig** [comment]
> already without this change a small file with a bigger buffer would end there

As far as I can see, this would result in `IOStatus.error` instead of `IOStatus.ok`, even if `IOMode.once` is specified.

> This change makes it so that when the buffer is larger than what a single read call will fill, it will stop there and not attempt to read the rest of the file or fill up the buffer

And I think the only realistic condition for this is that EOF is hit before the buffer has been filled completely. Maybe there is some system memory dependence that can also trigger this, but at least I couldn't find any hint of such a thing. But regardless, a test that tries to use machine limits in a CI worker with likely multiple other CI jobs running in parallel is probably not a stable solution.

**Comment by WebFreak001** [comment]
had this originally for reading from stdin, but decided to implement a separate stdin system now, because on windows it's like a file and on posix it's like a pipe - this didn't turn out to be used there

**Pull request closed without merging**
