### PR TITLE
Lazy driver initialization

### PR DESCRIPTION
**Pull request by s-ludwig**
This switches the initialization from `static this` to lazy singleton-style. Since the `eventDriver` property is marked `@nogc`, this required making a lot of the code `@nogc`, too. As a side-effect, this brings the codebase a good step closer to being better-C compatible.

The main advantage of this change is that it avoids useless initialization and shutdown, as well as resource use for threads that don't use the library at all. There also have been some crashes in such threads (caused by a compiler bug), which gets side-stepped by this.

### CODE REVIEW

**Comment by s-ludwig** [comment]
Merging in. Note that this has been stress tested in a vibe.d/webserver scenario, as well as in a multi-threaded desktop application, but any additional review is of course welcome dure to the critical nature of the changes.

**Comment by wilzbach** [comment]
Well this broke the project tester :/
Any chance we can revert this for now until this can be tested more thoroughly?

**Comment by wilzbach** [comment]
Disabled the vibe.d (built with vibe-core) tests for now: https://github.com/dlang/ci/pull/326

**Comment by wilzbach** [comment]
Buildkite PR to re-enable Vibe.d once this regression has been fixed: https://github.com/dlang/ci/pull/327 (it's currently partially disabled).

**Comment by s-ludwig** [comment]
Opened a fix: #87

It's not really a bug, but rather a missing workaround for a higher-level bug, which should be back in better form with that PR.

**Pull request merged**
